all: Random_Case Locality_Case Myref_Case
Random_Case: Page_Replacement_Algo.hpp Page_Replacement_Algo.cpp Random_Case.cpp
	g++ Page_Replacement_Algo.hpp Page_Replacement_Algo.cpp Random_Case.cpp -o Random_Case

Locality_Case: Page_Replacement_Algo.hpp Page_Replacement_Algo.cpp Locality_Case.cpp
	g++ Page_Replacement_Algo.hpp Page_Replacement_Algo.cpp Locality_Case.cpp -o Locality_Case

Myref_Case: Page_Replacement_Algo.hpp Page_Replacement_Algo.cpp Myref_Case.cpp
	g++ Page_Replacement_Algo.hpp Page_Replacement_Algo.cpp Myref_Case.cpp -o Myref_Case